#version: '3.8'

services:
  ollama:
    image: ollama/ollama
    user: root
    container_name: ollama
    ports:
      - '11434:11434'
    volumes:
      - ./backend/common/ollama:/root/.ollama
    networks:
      - backend
    restart: unless-stopped

  mongodb:
    image: mongo
    user: root
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./backend/common/errors/logs/mongod.log:/var/log/mongodb/mongod.log
    networks:
      - backend
    restart: unless-stopped

  backend:
    user: root
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./backend/common/errors/logs:/backend/common/errors/logs
    networks:
      - backend
    restart: unless-stopped

  frontend:
    user: root
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
