#version: '3.8'

services:
  frontend:
    user: root
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - backend
    restart: unless-stopped

  backend:
    user: root
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./backend/common/errors/logs:/backend/common/errors/logs
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
